# the followibg should all be done through this file:
# aberdeen
# apps
# cbim desktop where users have root
# public desktop
# banyan, bodhi
# research servers
# srinivas 100 g servers
# kerberos login
# dev systems linux-admn and root
# wordpress systems

# things done manually
# netapp
# git.lcsr
# hanz vm servers


# separate manual
# ? stag.autolab
# git.lcsr
# ? hackerspace servers
# ? ambari UI
# ? esxi
# ? macos vmware images
# ? netapp
# ? panic servers c231
# ? public windows10 server admin
# ? stratus superuser
# ? hanz vm
# ? vm image
# ? lcsr vpn

# not doing
# mandellian data
# zepplein admin
# university oracle
# jetsons
# ssl certs
# sites.cs mysql password
# quantum tape control
# podium hangout systems
# UPS's
# lobby pi
# ldap passwords
# lcsr oracle
# influx admin
# gmail and google stuff
# hadoop services
# kerberos / database etc
# brooklyn
# cbim ups
# cisco dell switches
# class vm 2020 spring
# conf room skype
# printers
# twitter
# ? credstat encryption
# elementor license
# ev1.cs.rutgers.edu - project nas box


---

# You'll need to run this with --ask-vault-pass, since
# the password hashes are stored encrypted using the ansible
# vault encryption

- hosts: all
  become: true

  tasks:

   - name: include encrypted variables for group
     include_vars: "password-data/{{ password }}.yml"

   - name: root password
     when: root_pass|default('') != ''
     lineinfile:
       path: /etc/shadow
       regexp: '^root:'
       line: "root:{{ root_pass }}:16651:0:99999:7:::"
       state: present

# generates an errr if linux-admin doesn't exist
   - name: see if linux-admin exists
     command: grep -q linux-admin /etc/passwd

   - name: linux-admin in /etc/shadow
     when: linux_admin_pass|default('') != ''
     lineinfile:
       path: /etc/shadow
       regexp: '^linux-admin:'
       insertafter: '^root:'
       line: "linux-admin:{{ linux_admin_pass }}:16731:0:99999:7:::"
       state: present      
