---

# You'll need to run this with --ask-vault-pass, since
# the password hashes are stored encrypted using the ansible
# vault encryption

- hosts: appsold apps special
  become: true

  tasks:

   - name: include encrypted variables for group
     include_vars: "password-data/{{ password }}.yml"

   - name: linux-admin in /etc/passwd
     lineinfile:
       path: /etc/passwd
       regexp: '^linux-admin:'
       insertafter: '^root:'
       line: 'linux-admin:x:1001:777::/home/linux-admin:/bin/bash'
       state: present
   - name: linux-admin in /etc/shadow
     when: linux_admin_pass|default('') != ''
     lineinfile:
       path: /etc/shadow
       regexp: '^linux-admin:'
       insertafter: '^root:'
       line: "linux-admin:{{ linux_admin_pass }}:16731:0:99999:7:::"
       state: present      
   - name: root password
     when: root_pass|default('') != ''
     lineinfile:
       path: /etc/shadow
       regexp: '^root:'
       line: "root:{{ root_pass }}:16651:0:99999:7:::"
       state: present
